# Домашнее задание 2 (pandas)

In [217]:
!pip install wget

Requirement already satisfied: wget in /usr/local/lib/python3.10/dist-packages (3.2)

In [16]:
import pandas as pd
import wget
import zipfile

## Импорт данных

In [17]:
url = 'https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip'
wget.download(url, 'Data.zip')

'Data.zip'

In [26]:
with zipfile.ZipFile('Data.zip', 'r') as zip_ref:
    zip_ref.extractall()

In [27]:
infos = []
marks = []

for i in range(10):
    infos.append(pd.read_csv(f'Data/Students_info_{i}.csv'))
    marks.append(pd.read_csv(f'Data/Students_marks_{i}.csv'))

## Задание 1

### Формулировка

Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.

### Код

In [90]:
df = pd.merge(pd.concat(infos, ignore_index=True, sort=False), (pd.concat(marks, ignore_index=True, sort=False)))

### Результат работы

In [91]:
df

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...,...
995,995,female,group E,master's degree,standard,completed,group10,88,99,95
996,996,male,group C,high school,free/reduced,none,group10,62,55,55
997,997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,998,female,group D,some college,standard,completed,group10,68,78,77
999,999,female,group D,some college,free/reduced,none,group10,77,86,86

## Задание 2

### Формулировка

Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

### Код

In [45]:
df = df.drop(columns=['index'])

### Результат работы

In [130]:
df.head(10)

,index,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
5,5,female,group B,associate's degree,standard,none,group1,71,83,78
6,6,female,group B,some college,standard,completed,group1,88,95,92
7,7,male,group B,some college,free/reduced,none,group1,40,43,39
8,8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,9,female,group B,high school,free/reduced,none,group1,38,60,50

## Задание 3

### Формулировка

Выведите на экран размеры полученной таблицы.

### Код

In [49]:
shape = df.shape

### Результат работы

In [50]:
shape

(1000, 9)

## Задание 4

### Формулировка

Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение).

### Код

In [62]:
numeric_row_characteristics = df.describe(include='number')

### Результат работы

In [63]:
numeric_row_characteristics

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

## Задание 5

### Формулировка

Проверьте, есть ли в таблице пропущенные значения.

### Код

In [80]:
rows_with_nans = df.loc[df.isna().any(axis=1)]

### Результат работы

In [79]:
print(rows_with_nans.size)
rows_with_nans

0

Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, group, math score, reading score, writing score]
Index: []

## Задание 6

### Формулировка

Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing).

### Код

In [82]:
means = df.mean(numeric_only=True)

### Результат работы

In [83]:
means

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

## Задание 7

### Формулировка

Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.

### Код

In [100]:
avg_grades = df.groupby(['test preparation course']).agg(avg_math=("math score", "mean"), avg_reading=("reading score", "mean"), avg_writing=("writing score", "mean"))

### Результат работы

In [101]:
avg_grades

                          avg_math  avg_reading  avg_writing
test preparation course
completed                69.695531    73.893855    74.418994
none                     64.077882    66.534268    64.504673

Можно заметить, что те, кто завершил курсы подготовки к сдаче экзаменов, в среднем, получали за экзамен по math на 5 баллов больше, по reading - на 7 баллов, по writing - на 10 баллов

## Задание 8

### Формулировка

Выведите на экран все различные значения из столбца lunch.

### Код

In [104]:
lunch_options = df["lunch"].unique()

### Результат работы

In [109]:
print(lunch_options)

['standard' 'free/reduced']

## Задание 9

### Формулировка

Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename.

### Код

In [111]:
df = df.rename(columns={
    'parental level of education': 'education',
    'test preparation course': 'test preparation'
})

### Результат работы

In [112]:
df

,index,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...,...
995,995,female,group E,master's degree,standard,completed,group10,88,99,95
996,996,male,group C,high school,free/reduced,none,group10,62,55,55
997,997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,998,female,group D,some college,standard,completed,group10,68,78,77
999,999,female,group D,some college,free/reduced,none,group10,77,86,86

## Задание 10

### Формулировка

**Ответьте на вопросы:**

Какая доля студентов сдала экзамен по математике (passmark >= 50)?

Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?

Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [29]:
passmark = 50

### Код

In [128]:
passed = len(df.loc[df['math score'] >= passmark]) / len(df)
prep_passed = len(df.loc[(df['math score'] >= passmark) & (df['test preparation'] == 'completed')]) / len(df.loc[df['test preparation'] == 'completed'])
woman_no_prep_failed = len(df.loc[(df['math score'] < passmark) & (df['test preparation'] == 'none') & (df['gender'] == 'female')]) / len(df.loc[(df['test preparation'] == 'none') & (df['gender'] == 'female')])

### Результат работы

In [129]:
print('Сдали:', passed, '\nПодготовились и сдали', prep_passed, '\nЖенщины, которые не готовились и не сдали:', woman_no_prep_failed)

Сдали: 0.865
Подготовились и сдали 0.9217877094972067
Женщины, которые не готовились и не сдали: 0.20958083832335328

## Задание 11

### Формулировка

**С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**

Для каждой этнической группы выведите средний балл за экзамен по чтению

Для каждого уровня образования выведите минимальный балл за экзамен по письму

### Код

In [176]:
%%timeit
df.groupby(['race/ethnicity']).agg(avg_ethnicity=('reading score', 'mean')) # довольно медленно

5.45 ms ± 1.02 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [177]:
df.groupby(['race/ethnicity']).agg(avg_ethnicity=('reading score', 'mean'))

                avg_ethnicity
race/ethnicity
group A             64.674157
group B             67.352632
group C             69.103448
group D             70.030534
group E             73.028571

In [178]:
%%timeit
df.groupby(['race/ethnicity'])["reading score"].mean() # ~в 7 раз быстрее

636 µs ± 46.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [179]:
df.groupby(['race/ethnicity'])["reading score"].mean()

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64

In [180]:
%%timeit
df.groupby(['education']).agg(min=('writing score', 'min')) # опять медленно!

7.49 ms ± 1.9 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [181]:
df.groupby(['education']).agg(min=('writing score', 'min'))

                    min
education
associate's degree   35
bachelor's degree    38
high school          15
master's degree      46
some college         19
some high school     10

In [182]:
%%timeit
df.groupby(['education'])['writing score'].min() # ~в 7 раз быстрее

675 µs ± 19.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [183]:
df.groupby(['education'])['writing score'].min()

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64

## Задание 12

### Формулировка

Выполните задание 11 с помощью циклов. Сравните время выполнения.

### Код

In [172]:
# оооочень долго (~в 7.5 раз медленнее чем agg и в 52 раза медленнее чем другой вариант)
%%timeit
counts = {}
sums = {}
output = {}
for i in range(len(df)):
    counts.setdefault(df['race/ethnicity'][i], 0)
    counts[df['race/ethnicity'][i]] += 1
    sums.setdefault(df['race/ethnicity'][i], 0)
    sums[df['race/ethnicity'][i]] += df['reading score'][i]

for key, value in sums.items():
    output[key] = value / counts[key]

39.1 ms ± 10.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [175]:
counts = {}
sums = {}
output = {}
for i in range(len(df)):
    counts.setdefault(df['race/ethnicity'][i], 0)
    counts[df['race/ethnicity'][i]] += 1
    sums.setdefault(df['race/ethnicity'][i], 0)
    sums[df['race/ethnicity'][i]] += df['reading score'][i]

for key, value in sums.items():
    output[key] = value / counts[key]


print(output)

{'group B': 67.35263157894737, 'group C': 69.10344827586206, 'group A': 64.67415730337079, 'group D': 70.03053435114504, 'group E': 73.02857142857142}

In [186]:
# настолько же дольше
%%timeit
mins = {}
for i in range(len(df)):
    mins.setdefault(df['education'][i], 1e50)
    mins[df['education'][i]] = min(mins[df['education'][i]], df['writing score'][i])

26.3 ms ± 5.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [ ]:
mins = {}
for i in range(len(df)):
    mins.setdefault(df['education'][i], 1e50)
    mins[df['education'][i]] = min(mins[df['education'][i]], df['writing score'][i])

print(mins)

## Задание 13

### Формулировка

Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выведите средний балл по каждому из предметов.

### Код

In [188]:
avg_score = df.groupby(['gender', 'education']).agg(avg_math=('math score', 'mean'), avg_reading=('reading score', 'mean'), avg_writing=('writing score', 'mean'))

### Результат работы

In [189]:
avg_score

                            avg_math  avg_reading  avg_writing
gender education
female associate's degree  65.250000    74.120690    74.000000
       bachelor's degree   68.349206    77.285714    78.380952
       high school         59.351064    68.202128    66.691489
       master's degree     66.500000    76.805556    77.638889
       some college        65.406780    73.550847    74.050847
       some high school    59.296703    69.109890    68.285714
male   associate's degree  70.764151    67.433962    65.405660
       bachelor's degree   70.581818    68.090909    67.654545
       high school         64.705882    61.480392    58.539216
       master's degree     74.826087    73.130435    72.608696
       some college        69.009259    64.990741    63.148148
       some high school    67.840909    64.693182    61.375000

## Задание 14

### Формулировка

Сколько студентов успешно сдали экзамен по математике?


Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

### Код

In [201]:
df['Math_PassStatus'] = df.apply(lambda row: 'F' if row['math score'] < passmark else 'P', axis=1)
df['Reading_PassStatus'] = df.apply(lambda row: 'F' if row['reading score'] < passmark else 'P', axis=1)
df['Writing_PassStatus'] = df.apply(lambda row: 'F' if row['writing score'] < passmark else 'P', axis=1)
df

,index,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P
1,1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P
2,2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F
4,4,male,group C,some college,standard,none,group1,76,78,75,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P
996,996,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P
997,997,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P
998,998,female,group D,some college,standard,completed,group10,68,78,77,P,P,P
999,999,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P

In [222]:
df.value_counts('Math_PassStatus')

Math_PassStatus
P    865
F    135
dtype: int64

In [220]:
df.value_counts('Reading_PassStatus')

Reading_PassStatus
P    910
F     90
dtype: int64

In [221]:
df.value_counts('Writing_PassStatus')

Writing_PassStatus
P    886
F    114
dtype: int64

## Задание 15

### Формулировка

Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

### Код

In [209]:
df['OverAll_PassStatus'] = df.apply(lambda row: 'P' if row['Math_PassStatus'] == row['Reading_PassStatus'] == row['Writing_PassStatus'] == 'P' else 'F', axis=1)
df

,index,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P
1,1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P
2,2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F
4,4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P,P
996,996,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P,P
997,997,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P,P
998,998,female,group D,some college,standard,completed,group10,68,78,77,P,P,P,P
999,999,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P,P

### Результат работы

In [213]:
df['OverAll_PassStatus'].value_counts()['P']

812

## Задание 16

### Формулировка

Переведем баллы в оценки

Система перевода баллов в оценки

больше 90 = A

80-90 = B

70-80 = C

60-70 = D

50-60 = E

меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).

### Код

In [215]:
def GetGrade(average_mark):
    if average_mark > 90:
        return 'A'
    if 80 <= average_mark <= 90:
        return 'B'
    if 70 <= average_mark < 80:
        return 'C'
    if 60 <= average_mark < 70:
        return 'D'
    if 50 <= average_mark < 60:
        return 'E'
    return 'F'

df['Grade'] = df.apply(lambda row: GetGrade((row['math score'] + row['reading score'] + row['writing score']) / 3), axis=1)
df

,index,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus,Grade
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P,C
1,1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P,B
2,2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P,A
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F,F
4,4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P,P,A
996,996,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P,P,E
997,997,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P,P,D
998,998,female,group D,some college,standard,completed,group10,68,78,77,P,P,P,P,C
999,999,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P,P,B

In [216]:
df['Grade'].value_counts()

C    261
D    256
E    182
B    148
F    103
A     50
Name: Grade, dtype: int64